- name: Installing nginx
  hosts: mongodb
  tasks: 
  - name: Installing nginx
    ansible.builtin.yum:
     name: nginx
     state: installed
  - name: Starting nginx
    ansible.bulitin.service:
      name: nginx
      state: started
