- name: Varibales from Promt
  hosts: mongodb
  vars_prompt: 
  - name: UserName
    promt: Enter your Name
    private: false
  - name: Password
    promt: Enter Password
    private: true
  tasks:
  - name: Printing Variables
    ansible.builtin.debug:
      msg: "{{UserName}} {{Password}}"